spring:
  profiles:
    active: local
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO              # 전체 로그 최소 INFO 이상 기록 :contentReference[oaicite:0]{index=0}
    org.springframework.web: INFO   # Spring MVC 디스패처 서블릿 로그 :contentReference[oaicite:1]{index=1}

gemini:
  api:
    key: ${GEMINI_API_KEY}

---
spring:
  config:
    activate:
      on-profile: local
    import: application-local.yml

---
spring:
  config:
    activate:
        on-profile: prod
    import: application-prod.yml